### PR TITLE
Hookup signup and login

### PR DESCRIPTION
**Pull request by CoreyAR**
- Renders one root component that sets the route component on change instead of rendering new on every route change
- Uses Context to manage a global user state
- Adds protected routes
- Persist auth between sessions
- Display signup/ login response errors

When this gets merged we should make tickets to:
- ~~Display signup/ login response errors~~
-  ~~Persist auth between sessions.~~

### CODE REVIEW

**Comment by CoreyAR** [comment]
Closes Issue #20 
Closes Issue #18

**Comment by Rian501** [comment]
I don't think we should be storing users' passwords in their profile data, but otherwise this is great. Thank you again for hooking this up!

**Comment by CoreyAR** [comment]
Can you help me see where we are storing the user's passwords? We are setting it in state during login and signup so we can use it in an api request. I don't think it is persisted anywhere. We could reset that field on submission also.

**Comment by Rian501** [comment]
I was looking at the database stored on firebase. I am not sure where it's getting attached to that object. I'll look into it.

**Comment by Rian501** [comment]
(but I figured we could merge this in and make that a new ticket if you prefer)

**Pull request merged**
