### PR TITLE
updated pw message to go with the regex check

### PR DESCRIPTION
**Pull request by Rian501**
The regex for password validation accepts letters (capitalized or not) and numbers only, so I have added that to the validation message for invalid passwords.
Closes issue #72

### CODE REVIEW

**Comment by CoreyAR** [comment]
The message change looks good. The PR is failing CI because of linting.

**Comment by Rian501** [comment]
I tried to fix that, but it's still having issues. Should I go ahead and merge it anyway or try to fix the lint first?

**Comment by Rian501** [comment]
I have disabled the VS Code setting that was adding those extra spaces, but now it looks like the spacing is off.

**Comment by CoreyAR** [comment]
The tests failing will prevent it from building. We should fix it in this PR so that we can keep dev and master green.

**Comment by Rian501** [comment]
yesss

**Pull request merged**
